{{ $fullname := include "surrogate.fullname" . }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $fullname }}-surrogate-config"
  namespace: {{ .Values.namespace }}
data:
  SURROGATE_MAP_FILE: "/app/data/example_map.json"
  SURROGATE_NAMES_DB_FILE: "/app/conf/surrogate_db/example_names.csv"
