{{ $fullname := include "surrogate.fullname" . }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $fullname }}-surrogate-map-config"
  namespace: {{ .Values.namespace }}
data:
  surrogate_map.json: |-
{{ .Files.Get "conf/surrogate/surrogate_map.json" | indent 4 }}
  surrogate_map.db.b64: {{ .Files.Get "conf/surrogate/surrogate_map.db" | b64enc | quote }}
