{{ $fullname := include "surrogate.fullname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ $fullname }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $fullname }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      volumes:
        - name: {{ $fullname }}-surrogate-names-vol
          configMap:
            name: {{ default (printf "%s-surrogate-names" (trim $fullname)) .Values.surrogate.surrogateNamesConfigMapName }}
        - name: {{ $fullname }}-surrogate-map-data-vol
          persistentVolumeClaim:
            claimName: {{ $fullname }}-map
      containers:
      - name: {{ $fullname }}
        image: {{ .Values.registry }}/{{ .Values.surrogate.name }}:{{ default .Chart.AppVersion .Values.tag }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.surrogate.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.surrogate.service.internalPort }}
        resources:
          requests:
            memory: {{ .Values.surrogate.container.resources.requests.memory }}
            cpu: {{ .Values.surrogate.container.resources.requests.cpu }}
          limits:
            memory: {{ .Values.surrogate.container.resources.limits.memory }}
            cpu: {{ .Values.surrogate.container.resources.limits.cpu }}
        envFrom:
          - configMapRef:
              name: {{ default (printf "%s-surrogate-config" (trim $fullname)) .Values.surrogate.defaultConfigMapName }}
        volumeMounts:
          - name: {{ $fullname }}-surrogate-names-vol
            mountPath: /app/conf/surrogate/example_names.csv
            subPath: example_names.csv
          - name: {{ $fullname }}-surrogate-map-data-vol
            mountPath: /app/data
      {{ if .Values.privateRegistry }}imagePullSecrets:
        - name: {{.Values.privateRegistry}}{{ end }}
