name: "Setup Nix Environment"
description: "Sets up Nix"

runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Enter dev shell and build CLI
      run: nix develop ./tools/nix#ci

    - name: bootstrap
      run: |
        ./tools/ci/setup-git.sh
      shell: bash
